### ISSUE TITLE
吹き出しっぽい感じにする

### ISSUE THREAD

**Issue by yuichiro12** [yuichiro12/bbs#52]
```css
.post-body {
    position: relative;
    display: inline-block;
    margin: 1.5em 0 1.5em 15px;
    padding: 15px 30px;
    min-width: 120px;
    max-width: 100%;
    color: #555;
    font-size: 16px;
    background: #FFF;
    border: solid 1px rgb(0, 145, 175);
    box-sizing: border-box;
    border-radius: 5px;
}

.post-body:before {
    content: "";
    position: absolute;
    top: 30px;
    left: -24px;
    margin-top: -12px;
    border: 12px solid transparent;
    border-right: 12px solid #FFF;
    z-index: 2;
}

.post-body:after {
    content: "";
    position: absolute;
    top: 30px;
    left: -27px;
    margin-top: -14px;
    border: 14px solid transparent;
    border-right: 14px solid rgb(0, 145, 175);
    z-index: -1;
}

```
